//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDB.EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_rder
    {
        public int Num_Order { get; set; }
        public int Id_Customer { get; set; }
        public int Id_Tool { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date_in { get; set; }
        public string Done { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tools Tools { get; set; }
    }
}
